services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SOCKET_URL: https://bkbajiapi.xyz
        NEXT_PUBLIC_SITE_URL: https://bkbaji.com
    ports:
      - "3020:3000" # VPS host 3020 (3000 is used by another service)
    environment:
      NODE_ENV: production
      API_URL: https://bkbajiapi.xyz
      GAME_LAUNCH_URL: https://apivexo.com/api/game/v1/gamelaunch
      GAME_API_SECRET: 483fb0fd241d4f37feea9dc36a7f00e669941c5837cff2aca072aa909f6be8f8
      GAME_API_PREFIX: CTT2J
      NEXT_PUBLIC_SITE_URL: https://bkbaji.com
      NEXT_PUBLIC_SOCKET_URL: https://bkbajiapi.xyz
    restart: unless-stopped

  dev:
    image: node:22-alpine
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      NEXT_PUBLIC_SOCKET_URL: http://localhost:8000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    profiles:
      - dev

volumes:
  node_modules:
